export enum ErrorNames {
  'BadRequest' = 'BadRequest',
  'NotAuthenticated' = 'NotAuthenticated',
  'PaymentError' = 'PaymentError',
  'Forbidden' = 'Forbidden',
  'NotFound' = 'NotFound',
  'MethodNotAllowed' = 'MethodNotAllowed',
  'NotAcceptable' = 'NotAcceptable',
  'Timeout' = 'Timeout',
  'Conflict' = 'Conflict',
  'LengthRequired' = 'LengthRequired',
  'Unprocessable' = 'Unprocessable',
  'TooManyRequests' = 'TooManyRequests',
  'GeneralError' = 'GeneralError',
  'NotImplemented' = 'NotImplemented',
  'BadGateway' = 'BadGateway',
  'Unavailable' = 'Unavailable',
  'Gone' = 'Gone',
}

export enum ErrorCodes {
  'BadRequest' = 400,
  'NotAuthenticated' = 401,
  'PaymentError' = 402,
  'Forbidden' = 403,
  'NotFound' = 404,
  'MethodNotAllowed' = 405,
  'NotAcceptable' = 406,
  'Timeout' = 408,
  'Conflict' = 409,
  'Gone' = 410,
  'LengthRequired' = 411,
  'Unprocessable' = 422,
  'TooManyRequests' = 429,
  'GeneralError' = 500,
  'NotImplemented' = 501,
  'BadGateway' = 502,
  'Unavailable' = 503,
}
